Adding in s3 HTTP challenge option
vancluever/terraform-provider-acme pull request #330
Opened 2023-08-01 11:01 UTC by kingcdavid

So in order for the s3 test to pass, we need to set up some env vars

TF_S3_BUCKET, this will need to be a real s3 bucket which you AWS creds have access to. if this is not set, it will skip the test
AWS_REGION, this will be the AWS region the s3 bucket is in

you will also have to have AWS credentials in your environment, this could be done in a number of ways:
https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/

2023-08-01 11:08 UTC, kingcdavid commented
example of working test:

```console
go test -v -run TestAccACMECertificate_httpS3      
=== RUN   TestAccACMECertificate_httpS3
2023/08/01 12:07:37 [INFO] acme: Registering account for nobody@example.test
2023/08/01 12:07:37 [INFO] acme: Trying to resolve account by key
2023/08/01 12:07:37 [INFO] acme: Trying to resolve account by key
2023/08/01 12:07:37 [INFO] [test-s3.example.test, test-s32.example.test] acme: Obtaining bundled SAN certificate
2023/08/01 12:07:37 [INFO] [test-s3.example.test] AuthURL: https://localhost:14000/authZ/Ds0h3OSt2VYuJ6Y8ntyeHMShD1cT8ZSLIwp6BP6csXg
2023/08/01 12:07:37 [INFO] [test-s32.example.test] AuthURL: https://localhost:14000/authZ/yh1JYvTqHcZMGaBYiZt5i3_p8Vzy15gb-Tq8iymn6tw
2023/08/01 12:07:37 [INFO] [test-s3.example.test] acme: Could not find solver for: tls-alpn-01
2023/08/01 12:07:37 [INFO] [test-s3.example.test] acme: use http-01 solver
2023/08/01 12:07:37 [INFO] [test-s32.example.test] acme: Could not find solver for: tls-alpn-01
2023/08/01 12:07:37 [INFO] [test-s32.example.test] acme: use http-01 solver
2023/08/01 12:07:37 [INFO] [test-s3.example.test] acme: Trying to solve HTTP-01
2023/08/01 12:07:40 [INFO] [test-s3.example.test] The server validated our request
2023/08/01 12:07:40 [INFO] [test-s32.example.test] acme: Trying to solve HTTP-01
2023/08/01 12:07:44 [INFO] [test-s32.example.test] The server validated our request
2023/08/01 12:07:44 [INFO] [test-s3.example.test, test-s32.example.test] acme: Validations succeeded; requesting certificates
2023/08/01 12:07:44 [INFO] Wait for certificate [timeout: 30s, interval: 500ms]
2023/08/01 12:07:44 [INFO] [test-s3.example.test] Server responded with a certificate.
2023/08/01 12:07:44 [INFO] acme: Trying to resolve account by key
2023/08/01 12:07:45 [INFO] acme: Trying to resolve account by key
2023/08/01 12:07:45 [INFO] acme: Trying to resolve account by key
2023/08/01 12:07:45 [INFO] acme: Deleting account for nobody@example.test
--- PASS: TestAccACMECertificate_httpS3 (9.27s)
PASS
ok  	github.com/vancluever/terraform-provider-acme/v2/acme	9.285s

```

2023-08-01 12:34 UTC, kingcdavid commented
N.b This is pulling from acme-go@latest, so i guess we should wait till 4.14.0 is released?

2023-08-01 16:22 UTC, vancluever requested changes
@kingcdavid thanks for taking this on!

So looks like there's some things that need to be done for sure here, ahead of the next release of lego:

* Formatting: Can you run your changes through [gofmt](https://pkg.go.dev/cmd/gofmt).
* Documentation: Can you add an appropriate section under the [HTTP/TLS challenge section](https://github.com/vancluever/terraform-provider-acme/blob/main/docs/resources/certificate.md#using-http-and-tls-challenges) in the resource docs.
* Tests: I see that this might require an actual S3 bucket to run - did you happen to try getting it working with LocalStack so that it could be included in CI? The GH actions are not wired to real resources and I'm not planning on adding any.

Thanks again!

2023-08-01 16:22 UTC, vancluever commented on acme/resource_acme_certificate_test.go
> +			Steps: []resource.TestStep{
@kingcdavid were these test files run though [`gofmt`](https://pkg.go.dev/cmd/gofmt)? This should likely be set up by your editor, but this indent looks out of place.

2023-08-01 16:22 UTC, vancluever commented on acme/resource_acme_certificate_test.go
> +		return
[`t.Skip(...)`](https://pkg.go.dev/testing#T.Skip) should be used to skip tests.

2023-08-01 16:22 UTC, vancluever commented on acme/resource_acme_certificate_test.go
> +
Looks like a stray newline possibly due to a `gofmt` being necessary?

2023-08-01 16:22 UTC, vancluever commented on acme/resource_acme_certificate_test.go
> +    }
@kingcdavid looks like this definitely needs to be run through `gofmt`, as this brace is out of place as well.

2023-08-01 17:23 UTC, kingcdavid commented
Hey @vancluever

Yes sorry I should have formatted it, and updated the docs. I went with real s3 testing as openstack seemed quite heavy, but i can look at that. It mention in the openstack docs it significantly modifies a host, so may look to run it in docker if I can? What's your thoughts?

Thanks

2023-08-01 18:01 UTC, vancluever commented
PS: it does look like [LocalStack has instructions for GH actions](https://docs.localstack.cloud/user-guide/ci/github-actions/), so it seems feasible we could use it.

You don't have to worry about that part though, so long as it works against a local endpoint that will be enough for me 🙂

2023-08-01 18:58 UTC, kingcdavid commented
Ah sorry LocalStack does make much more sense

Though looking at the config, i'd have to make an upstream change to lego in order to point the AWS SDK to a local endpoint
i.e. https://github.com/localstack/localstack-aws-sdk-examples/blob/main/go/s3-basic-v2.go
which could get a little messy, unless you can think of a way to proxy it to local stack?

2023-08-01 19:22 UTC, vancluever commented
Ah yeah, I see how the example uses the endpoint overrides in the SDK - we definitely don't want to use those. Looks like transparent endpoint injection is a pro feature too.

I think the fact that this is testable on S3 is good enough for now then! So long as the code remains relatively static and we can do ad hoc testing, I think that'll be fine. I might investigate other options just in case, but otherwise it should be okay.

2023-08-22 23:51 UTC, vancluever reviewed
Just documenting some necessary changes that I'm going to do to get this over the line, don't worry about doing anything here @kingcdavid :slightly_smiling_face:

2023-08-22 23:51 UTC, vancluever commented on acme/resource_acme_certificate_test.go
> +		t.Skip()
_Note for @vancluever_ add a warning here mentioning that the test will be skipped due to missing env var

2023-08-22 23:51 UTC, vancluever commented on acme/resource_acme_certificate_test.go
> +		panic(fmt.Errorf("TestAccACMECertificate_S3httpProxy: %s", err))
_Note for @vancluever_ fail test here instead of `panic()`

2023-08-22 23:51 UTC, vancluever commented on go.mod
> +	github.com/go-acme/lego/v4 v4.13.4-0.20230727185640-f582d12f6580
_Note for @vancluever_ update/bump this to v4.14.0

2023-08-23 02:52 UTC, vancluever approved these changes
Merging this now! Thanks again for the contribution @kingcdavid!

2023-08-23 03:02 UTC, merged